name: test-python-versions
on: 
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Test Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-vresion: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install sade
        run: |
          python -m pip install --upgrade pip
          pip install .
          sade -v